[package]
name = "startup-map-embedding"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3.1"
fastembed = "5.0.2"
ndarray = "0.16.1"
pacmap = { version = "0.2.6", features = ["openblas-static"] }
serde = { version = "1.0.219", features = ["derive"] }
