[package]
name = "visualization"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3.1"
dioxus = { version = "0.6.3", features = ["web"] }
serde = { version = "1.0.219", features = ["derive"] }
gloo-timers = { version = "0.3.0", features = ["futures"] }
